General project cleanup

diff --git a/libexec/bowenos/bowenos-update b/libexec/bowenos/bowenos-update
--- a/libexec/bowenos/bowenos-update
+++ b/libexec/bowenos/bowenos-update
@@ -11,12 +11,8 @@ if [[ -f /etc/bowenos/flake.nix ]]; then
   if [[ -e /dev/disk/by-partlabel/disk-bootB-esp ]]; then
     ensure_mountpoint /bootB "disk-bootB-esp"
   fi
-  extra_flags=()
-  if [[ -d /tmp/installer ]]; then
-    extra_flags+=(--override-input bowenos "path:/tmp/installer")
-  fi
-  sudo nixos-rebuild switch --impure --flake "path:/etc/bowenos#${HOST}" "${extra_flags[@]}"
+  sudo nixos-rebuild switch --refresh --impure --flake "path:/etc/bowenos#${HOST}"
 else
-  echo "Missing /tmp/bowenos" >&2
+  echo "Missing /etc/bowenos" >&2
   exit 1
 fi
